### ISSUE TITLE
WX14 Bugs

### ISSUE THREAD

**Issue by webxoss** [webxoss/webxoss-core#23]
## Bugs:

- [x] #31  WX13-029 3rd effect also affects LRIG

- [ ] Const Effect WX05-019

- [x] #29  WX12-046 WX12-047 attack count

- [x]  【无法重现】对手城堡代号在场 我方创世超越1效果发动 之后我方sign "出"仍不能发动

- [ ] 双色皮露露可 小剑三日月  不能代替黑色费用支出

- [x] #30  The Cobra, Phantom Dragon (WX14-041) on-play effect works incorrect. The red card is considered as a green one in on-play condition, and the green card is considered as a red one.

- [x] 【not a bug】`Code Love Heart †MCMR†` It seems that I can only use the action effect once or twice, although her "Action effect" button is still on, I keep clicking it but nothing happens.Sometimes, I can't even use her action due to bug.

- [x] 【无法重现】艾娅伊战斗阶段用水天一碧将胡桃夹子从能量区移回手牌时效果没有发动

- [x] #28 `白罗星 阋神星`《精罗：宇宙》

- [x] #28 蝙蝠车缺少武装判断

- [x] #28 对方场上 大白鲨，我方场上爱心代号cmr（五级蓝电机），我方被踹出生命爆发，选择了发动，为什么对方大白鲨仍能抽卡，竖直其精灵？

- [x] spellCutIn in attackPhase
- [x] WX14-026
- [x] WX11-032 with WX14-017
- [x] PR-307 not ignore timing
- [x] WX14-047
- [x] WX05-013
- [x] PR-309
- [x] WX14-009
- [x] PR-307 Ener cost in opponent's turn
- [x] WD13-010 Leave field and attack again
- [x] WX14-018 SIGNI attack directly
- [x] PR-212 Action effect is activated on field
