### ISSUE TITLE
[Test] WX15 checklist

### ISSUE THREAD

**Issue by webxoss** [webxoss/webxoss-core#40]
- [x] [红]PR-308
- [x] [白/黑]PR-322
- [x] [白]PR-323
- [x] [红]PR-324
- [x] [蓝]PR-325
- [x] [绿]PR-326
- [x] [黑]PR-327
- [x] [红]PR-330
- [x] [蓝]PR-331
- [x] [绿]PR-332
- [x] [蓝]PR-340
- [x] [黑]PR-341
- [x] [白]PR-342
- [x] [红]PR-343
- [x] [蓝]PR-344
- [x] [绿]PR-345
- [x] [绿]PR-346
- [x] [黑]PR-347
- [x] [红]PR-350
- [x] [蓝]PR-351
- [x] [绿]PR-352
- [x] [黑]PR-353
- [x] [白]SP20-001
- [x] [红]SP20-002
- [x] [蓝]SP20-003
- [x] [绿]SP20-004
- [x] [绿]SP20-005
- [x] [黑]SP20-006
- [x] [红]WD10-012
- [x] [红]WX15-001
- [x] [蓝]WX15-002
- [x] [绿]WX15-003
- [x] [黑]WX15-004
- [x] [红]WX15-005
- [x] [绿]WX15-006
- [x] [红]WX15-007
- [x] [红]WX15-008
- [x] [红]WX15-009
- [x] [红]WX15-010
- [x] [红]WX15-011
- [x] [蓝]WX15-012
- [x] [蓝]WX15-013
- [x] [蓝]WX15-014
- [x] [蓝]WX15-015
- [x] [蓝]WX15-016
- [x] [蓝]WX15-017
- [x] [绿]WX15-018
- [x] [绿]WX15-019
- [x] [绿]WX15-020
- [x] [绿]WX15-021
- [x] [绿]WX15-022
- [x] [黑]WX15-023
- [x] [黑]WX15-024
- [x] [黑]WX15-025
- [x] [黑]WX15-026
- [x] [黑]WX15-027
- [x] [黑]WX15-028
- [x] [无]WX15-029
- [x] [无]WX15-030
- [x] [白]WX15-031
- [x] [红]WX15-032
- [x] [红]WX15-033
- [x] [红]WX15-034
- [x] [蓝]WX15-035
- [x] [蓝]WX15-036
- [x] [绿]WX15-037
- [x] [绿]WX15-038
- [x] [黑]WX15-039
- [x] [黑]WX15-040
- [x] [红]WX15-041
- [x] [红]WX15-042
- [x] [红]WX15-043
```
"q": "このシグニの上に《ライズ》を持つシグニが置かれてカードを引いた後、さらにその上に《ライズ》を持つシグニが置かれた場合、この能力は発動しますか？"
"a": "いいえ、場にあるこのシグニの上に置かれたわけではありませんので発動しません。"

"q": "《グレイブ・ラッシュ》によって場に出た《一途の帰蝶　ノヒメ》にシグニがライズしました。ライズされた時の自動能力は発動しますか？また、ターン終了時に、この《一途の帰蝶　ノヒメ》またはライズしたシグニはトラッシュに置かれますか？"
"a": "能力を失っていますので、自動能力は発動しません。\nシグニの下にあるカードは以前としてシグニですが、レベルやリミットの参照に含まれませんし、シグニに対する効果の影響も受けませんので、《グレイブ・ラッシュ》によって場に出た《一途の帰蝶　ノヒメ》およびそれにライズしたシグニをターン終了時に場からトラッシュに置くことはありません。"
```
- [x] [红]WX15-044
- [x] [红]WX15-045
- [x] [红]WX15-046
- [x] [蓝]WX15-047
- [x] [蓝]WX15-048
- [x] [蓝]WX15-049
- [x] [蓝]WX15-050
- [x] [蓝]WX15-051
- [x] [蓝]WX15-052
- [x] [蓝]WX15-053
- [x] [绿]WX15-054
- [x] [绿]WX15-055
- [x] [绿]WX15-056
- [x] [绿]WX15-057
- [x] [绿]WX15-058
- [x] [绿]WX15-059
- [x] [绿]WX15-060
- [x] [黑]WX15-061
- [x] [黑]WX15-062
- [x] [黑]WX15-063
- [x] [黑]WX15-064
- [x] [黑]WX15-065
- [x] [黑]WX15-066
- [x] [黑]WX15-067
- [x] [红]WX15-068
- [x] [红]WX15-069
```
"q": "バニッシュされたときの能力で支払う《赤》は、バニッシュされた《炎身の南王　シュクユ》自身で支払えますか？"
"a": "はい、可能です。その場合でもそのまま効果を処理し、デッキからシグニを探すことができます。"
```
- [x] [红]WX15-070
```
"q": "【トリプルクラッシュ】を持った《矜持の豪魔　オダノブ》に、《聖身の円卓　ボールス》の能力で【ダブルクラッシュ】を与えた場合はどうなりますか？"
"a": "その場合、【トリプルクラッシュ】により3枚同時にクラッシュとなります。2枚や5枚クラッシュするわけではありません。"
```
- [x] [红]WX15-071
- [x] [红]WX15-072
- [x] [红]WX15-073
- [x] [红]WX15-074
- [x] [红]WX15-075
- [x] [红]WX15-076
- [x] [红]WX15-077
- [x] [红]WX15-078
- [x] [红]WX15-079
- [x] [红]WX15-080
- [x] [蓝]WX15-081
- [x] [蓝]WX15-082
- [x] [蓝]WX15-083
- [x] [蓝]WX15-084
- [x] [蓝]WX15-085
- [x] [蓝]WX15-086
- [x] [蓝]WX15-087
- [x] [蓝]WX15-088
- [x] [蓝]WX15-089
- [x] [蓝]WX15-090
- [x] [蓝]WX15-091
- [x] [蓝]WX15-092
- [x] [绿]WX15-093
- [x] [绿]WX15-094
- [x] [绿]WX15-095
- [x] [绿]WX15-096
```
"q": "正面以外のシグニゾーンにアタックした場合、どうなりますか？"
"a": "そこにシグニがあれば、そのシグニとのバトルとなります。シグニが無いのであれば、そのアタックでは何も起こりません。（バトルもせず、対戦相手にダメージも与えません。）"
```
- [x] [绿]WX15-097
- [x] [绿]WX15-098
- [x] [绿]WX15-099
- [x] [绿]WX15-100
- [x] [绿]WX15-101
- [x] [绿]WX15-102
- [x] [绿]WX15-103
- [x] [绿]WX15-104
- [x] [绿]WX15-105
- [x] [绿]WX15-106
- [x] [黑]WX15-107
- [x] [黑]WX15-108
- [x] [黑]WX15-109
- [x] [黑]WX15-110
- [x] [黑]WX15-111
- [x] [黑]WX15-112
- [x] [黑]WX15-113
- [x] [黑]WX15-114
- [x] [黑]WX15-115
- [x] [黑]WX15-116
- [x] [黑]WX15-117
- [x] [黑]WX15-118
- [x] [无]WX15-119
- [x] [无]WX15-120
- [x] [无]WX15-121
- [x] [无]WX15-122
- [x] [无]WX15-123
- [x] [红]WX15-Re01
- [x] [黑]WX15-Re02
- [x] [红]WX15-Re03
- [x] [红]WX15-Re04
- [x] [红]WX15-Re05
- [x] [蓝]WX15-Re06
- [x] [蓝]WX15-Re07
- [x] [蓝]WX15-Re08
- [x] [绿]WX15-Re09
- [x] [绿]WX15-Re10
- [x] [绿]WX15-Re11
- [x] [绿]WX15-Re12
- [x] [黑]WX15-Re13
- [x] [黑]WX15-Re14
- [x] [黑]WX15-Re15

**Comment by bunlion** [comment]
WX15-050    * 发动效果不需要横置

WX15-089    * 检查对手的signi是否满足攻击力大小，应该是按自己signi攻击力大小处理了。
WX15-090    * 检查对手的signi是否满足攻击力大小，应该是按自己signi攻击力大小处理了。
WX15-091    * 检查对手的signi是否满足攻击力大小，应该是按自己signi攻击力大小处理了。

**Comment by webxoss** [comment]
@bunlion 
WX15-050 * 发动效果不需要横置
fixed in e5f7997

WX15-089 * 检查对手的signi是否满足攻击力大小，应该是按自己signi攻击力大小处理了。
WX15-090 * 检查对手的signi是否满足攻击力大小，应该是按自己signi攻击力大小处理了。
WX15-091 * 检查对手的signi是否满足攻击力大小，应该是按自己signi攻击力大小处理了。
fixed in 758ad83

**Comment by sssuwako** [comment]
- [x] WX15-001	起效果，第二段效果应该是公开自己的，而不是对面的
Not a bug

- [x] WX15-044	使用效果应该横置
fixed in 495d1e9

- [x] WX15-070	应该是给我方的升阶怪上BUFF，而不是对面的任意怪
fixed in 17830da

- [x] WX15-043	效果不发动
fixed in f88ffca

- [x] WX15-046	效果不发动
fixed in c6ee9f7

- [ ] WX15-033	迸发：应该是对面选手牌或能量区;能不能选场上不清楚

- [ ] WX15-005	没测

其他红色大概没问题

@sssuwako

**Comment by webxoss** [comment]
```
PR-341 出场不能获得硬币
PR-347 出场不能获得硬币
SP20-006 出场不能获得

fixed in 68686c59ecfde9b0383d8851c2da7ce38a5677ee
```

```
【无名 其四之别】wx15-004 期效果不能发动

**未实现**
```

```
【白亚的键主 乌姆尔】PR-322 翻译为日文没有测试

**待测试**
```

SIGNI：

```
【死之游 †溜溜球†】wx15-107 效果不能正常发动（不能横置）

**代码上看没问题，待确认**
```

```
【惨之游 †转碟†】wx15-108  出场效果不正常（应为-7000实测+7000）

fixed in 71f2d32ad2da9039ace975c1080b86ced27ede3d
```

```
【似之游 †恰吉†】wx15-062  出场效果不正常（可以拉3J精灵，有一定可能出bug）

中文翻译有误，应为3以下，已修复。
```

```
【似之游 †雪茄盒†】wx15-109  出场效果不正常（应为-3000实测+3000）
【异血之游 †剑玉†】wx15-110  出场效果不正常（应为-1000实测+3000）

fixed in 48b7db9cc615ad3587dc6dcecd3db09f8c750c5a
```

```
【死之游姬 †日本人偶†】wx15-039  自效果发动不能

fixed in 453881fbdef6c32fbd9be36058f3daad561ee9cf
**（对这个 fix 不自信，麻烦再测一下。）**
```

魔法和技艺

```
【黑色束缚】wx15-118 出bug

fixed in c35332714ef76b8a879170dbc4ace9ed2c3efb7a
```

```
【反常恋人】wx15-028 出bug

fixed in 94a2687113b41603d7a5d40bc5ffef4fee428402
```

```
【溶解制造】wx15-067 出bug

fixed
```

关于罗菌：先吃饭回点血
关于re卡：不想测，但是毒匕首的效果起发动不能（吃完饭把re卡以前的卡的代号给你）

wx15-re01  炎固 wx07-011
           02   鲜斩 wx02-020
           03   小炮 wx10-065
           04   cyua wx06-CB01
           05   割裂  pr-053
           06   tap   wx06-CB02
           07   冰穿  wx07-065
           08   3出   wx01-084
           09   花音  wx03-032
           10   牙膏  wx06-CB03
           11   仙客来 wx11-080
           12   3剑     pr-207
           13   毒匕首 wx04-101（re卡效果不能发动）
           14   巴勒贝克 wx02-042
           15   法师    pr-212

**Comment by webxoss** [comment]
Done
